name: eslint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
#     steps:
#       - uses: hallee/eslint-action@1.0.3
#         if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}
#         with:
#           repo-token: ${{secrets.GITHUB_TOKEN}}
#           source-root: optional-sub-dir

    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2.1.0
        - name: Install Modules
          run: npm install -g eslint
        - name: Run eslint
          run: eslint .
